from flask import Blueprint, request, jsonify
import sys
import os

# Ensure the current directory is in sys.path so that internal modules (like answer, retrieval) can be imported by answer.py
# answer.py does this too, but doing it here ensures safety if we import answer differently.
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.append(current_dir)

try:
    from .answer import answer_question
    from .sql_agent import run_sql_agent
except ImportError:
    # Fallback if relative import fails (e.g. if run directly)
    from answer import answer_question
    from sql_agent import run_sql_agent

rag_bp = Blueprint('rag', __name__, url_prefix='/api')

@rag_bp.route("/chat", methods=["POST"])
def rag_chat():
    """
    RAG Chat Interface
    URL: /api/chat
    Method: POST
    Body: { "question": "...", "type": "rag" | "sql" }
    """
    data = request.get_json(silent=True) or {}
    question = data.get("question", "").strip()

    def is_sql_query(question):
        keywords = ['查询', '统计', '多少', '最大', '最小', '平均', '总数', '排名', '明细', '列表', '数据', '表', 'SQL', 'select', 'count', 'sum']
        return any(k in question for k in keywords)

    chat_type = data.get("type")
    if not chat_type:
        chat_type = "sql" if is_sql_query(question) else "rag"

    if not question:
        return jsonify({
            "message": "question is required",
            "answer": "",
            "sources": []
        }), 400

    try:
        if chat_type == "sql":
            # 调用 SQL Agent
            answer = run_sql_agent(question)
            return jsonify({
                "answer": answer,
                "sources": [{"source": "MySQL Database", "content": "Generated by SQL Agent"}],
                "message": "success"
            })
        else:
            # 调用 RAG
            result = answer_question(question)
            return jsonify(result)
            
    except Exception as e:
        print(f"Chat Error: {e}")
        return jsonify({
            "message": str(e),
            "answer": "抱歉，系统暂时无法回答您的问题。",
            "sources": []
        }), 500
